# Основные параметры проекта
sonar.projectKey=JavaInDocker
sonar.projectName=JavaInDocker
sonar.projectVersion=1.0

# Путь к исходному коду приложения
sonar.sources=src/main/java

# Путь к исходному коду тестов
sonar.tests=src/test/java

# Исключения (файлы, которые не нужно анализировать)
sonar.exclusions=**/generated/**,**/mystatic/**

# Язык программирования проекта
sonar.language=java

# Пути к отчетам о тестировании (раскомментируйте при использовании JUnit)
# sonar.junit.reportPaths=target/surefire-reports

# Пути к отчетам о покрытии кода (раскомментируйте при использовании JaCoCo)
# sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Настройки подключения к базе данных SonarQube
sonar.jdbc.url=jdbc:mysql://localhost/sonarqube
sonar.jdbc.username=admin
sonar.jdbc.password=admin

# Интеграция с системой контроля версий
sonar.scm.provider=git

###############################################
# Команды для запуска анализа через терминал
#
# Вариант 1 (через login):
# sonar-scanner -Dsonar.host.url=http://localhost:9000 -Dsonar.login=sqp_6c049b2b4149aaf34c9acd953ee7e2d1519fbdf5
#
# Вариант 2 (через token):
# sonar-scanner -Dsonar.host.url=http://localhost:9000 -Dsonar.token=sqp_6c049b2b4149aaf34c9acd953ee7e2d1519fbdf5 -Dsonar.projectKey=JavaInDocker -Dsonar.sources=.
###############################################